# Generated by Django 4.2.7 on 2025-08-08 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='IELTS Listening Test', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('total_duration', models.PositiveIntegerField(default=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listening_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListeningUserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_answers', models.PositiveIntegerField()),
                ('answers', models.JSONField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('practice', 'Practice Mode'), ('exam', 'Exam Mode')], default='exam', max_length=20)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='tests.listeningtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listening_user_results',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='ListeningSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('transcript', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tests.listeningtest')),
            ],
            options={
                'db_table': 'listening_sections',
                'ordering': ['section_number'],
                'unique_together': {('test', 'section_number')},
            },
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('radio', 'Multiple Choice'), ('dropdown', 'Matching/Dropdown'), ('text', 'Text Input'), ('multi_choice', 'Multiple Choice (Checkbox)'), ('labeling', 'Plan/Map/Diagram Labeling'), ('completion', 'Form/Note/Table/Flowchart Completion'), ('sentence_completion', 'Sentence Completion'), ('short_answer', 'Short Answer')], max_length=20)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField(default=1)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.listeningsection')),
            ],
            options={
                'db_table': 'listening_questions',
                'ordering': ['order'],
                'unique_together': {('section', 'order')},
            },
        ),
    ]
