# Generated by Django 4.2.7 on 2025-08-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_listeningtest_listeninguserresult_listeningsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningsection',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='listening_audios/'),
        ),
    ]
