# Generated by Django 4.2.7 on 2025-08-30 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0004_listeningsection_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='IELTS Writing Test', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('task1_image', models.TextField(blank=True, null=True)),
                ('task1_image_description', models.TextField(blank=True, null=True)),
                ('task1_type', models.CharField(choices=[('graph', 'Graph'), ('chart', 'Chart'), ('table', 'Table'), ('diagram', 'Diagram'), ('map', 'Map')], default='graph', max_length=50)),
                ('task2_essay_prompt', models.TextField()),
                ('task2_type', models.CharField(choices=[('opinion', 'Opinion-based'), ('problem_solution', 'Problem-Solution'), ('discussion', 'Discussion'), ('advantage_disadvantage', 'Advantage-Disadvantage')], default='opinion', max_length=50)),
                ('task1_time_limit', models.PositiveIntegerField(default=20)),
                ('task2_time_limit', models.PositiveIntegerField(default=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'writing_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingTestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task1_answer', models.TextField()),
                ('task2_answer', models.TextField()),
                ('task1_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('task1_feedback', models.TextField(blank=True, null=True)),
                ('task2_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('task2_feedback', models.TextField(blank=True, null=True)),
                ('overall_band_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('task1_criteria', models.JSONField(blank=True, null=True)),
                ('task2_criteria', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('task1_time_taken', models.DurationField(blank=True, null=True)),
                ('task2_time_taken', models.DurationField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tests.writingtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'writing_test_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
